name: format

on:
  push:
    branches:
    - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: install
      run: |
        pip3 install --upgrade pip
        pip3 install black blackdoc isort
    - name: format
      run: |
        make format
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Apply formatter'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
